# Step 5 (preparation)
# This query is run against the converted dataset
# (roberts conversion from 2008-11-10)
# to extract 
#   audiences 
# 

base <http://detektor.sublima.computas.com:8180/detektor/> 
prefix audience:   <audience/> 
prefix sioc: 		<http://rdfs.org/sioc/ns#> 
prefix rdfs: 		<http://www.w3.org/2000/01/rdf-schema#>
prefix wdr: 		<http://www.w3.org/2007/05/powder#> 
prefix dct: 		<http://purl.org/dc/terms/> 


CONSTRUCT { 
   ?audience a dct:AgentClass .
   ?audience rdfs:label ?label .
} 
WHERE {
   ?audience a dct:AgentClass .
   ?audience rdfs:label ?label .
}